### ISSUE TITLE
Add new scripts for scans

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#108]
This is to make usage more convenient for users. @mariavd will take care of this

**Comment by mariavd** [comment]
@bast I updated a few things on the scripts this weekend, and I think I can now ask them to be merged to upstream. There are still things to improve but at least they feel more tidy. I would like to keep the git history for my branch, but it has a huge number of commits because I have been working on them for over an year already. Should I make a new branch from the HEAD of my `jobscripts` branch, rebase everything into one commit on the new branch and do a PR for it? 

Also, since I am continuously working on them, I guess I will keep the latest changes to my fork but only PR only some major changes? I am asking since sometimes I work on them daily and it might be a bit annoying to swamp you with requests. 

And I hope that @heikef will give them a try and as much feedback as possible. My goal for them is to be user-friendly and helpful, not yet another thing a new user has to master. A documentation page is on the way, too.

**Comment by bast** [comment]
From my perspective it is not a problem to send many PRs. Also not a problem to send many commits if the commits are self contained. If not, squash them. You don't have to squash them into one, but squash them into logical units. It's good plan to keep your branch and edit commits on a copy branch.

**Comment by heikef** [comment]
@mariavd Thank you. I have a complicated molecule I need to investigate, a perfect case for your scripts. Looking forward to test. Please share when you are ready.
