### ISSUE TITLE
Reintroduce parallellization

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#114]
Some fine tuning and checks are needed to make the program work in parallel. This is part of the AUS project of @bast and @heikef

**Comment by bast** [comment]
I am now working on it. A little bit more than fine-tuning is needed. The parallel code is simply broken.

**Comment by heikef** [comment]
Yes, the first impression was a bit too optimistic. However, it is very important to fix this issue. Thanks for working on this.

**Comment by bast** [comment]
So after a day of poking in the code I am at a point where we need to plan next steps:

The code is reading input from stdin but it is not trivial to channel stdin to all workers.

I have tried that only one tasks reads and then settings are distributed but this is hard because of complex data structures which are hard to synchronize. In the long term the data structures need to be simplified.

What could work in the short term is that the input file is not read from stdin but given as a positional argument. This is an easy change but will break all current run scripts :-)

Preferences?

**Comment by bast** [comment]
Sorry what I wrote is not correct - it seems that the reading can be changed since it only happens inside the gimic script. It would only break for people who do not use the gimic script.

**Comment by heikef** [comment]
I am confused now. But I hesitate "destroying" all the scripts we have. -))

**Comment by bast** [comment]
So am I - the code is incredibly complex and complicated :-) How do most people run GIMIC?

**Comment by bast** [comment]
We try OMP first. MPI might require to abandon stdin reading in gimic script.

**Comment by heikef** [comment]
Yes, after our discussion I agree with this roadmap. We should not abandon though MPI.

**Comment by bast** [comment]
OMP parallelization seems to be more or less intact but some tests fail so I need to look into that but possibly not much needs to be done.

**Comment by heikef** [comment]
Good. Let's get this work first and then look into MPI.

**Comment by bast** [comment]
Splitting this into two issues: #168 and #169. Closing this ticket.
