### ISSUE TITLE
Introduce streamline integration

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#115]
It would be great to have a two color type visualization for dia- and paratropic currents. This direction dependency is not yet possible with Paraview.

**Comment by mariavd** [comment]
I think this issue should be renamed to "Introduce streamline integration" or something similar. It is a fundamental issue with our method, rather than just a visualization problem. After the long discussions this spring we came to the conclusion that the local information that we obtain at each point is not enough to determine a global property such as current tropicity.

**Comment by bast** [comment]
renamed

**Comment by heikef** [comment]
This issue is very old. Nobody worked on this. I will close it. We can reopen it if needed be.
