### ISSUE TITLE
ifort compiled code much faster than gfortran compiled code

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#123]
I got a mail from Dage stating that gimic compiled with gfortran is faster than compiled with ifort. This sounds strange to me. We need to check this and set up an example. @mariavd and @lnw could you help with this? I remember you were looking before into timings so you might already have an example to share.

**Comment by mariavd** [comment]
No, it is the other way around. Intel compilers make the code much faster. This is of course expected because Intel know their CPUs better and how to make smarter choices of instructions in the binary. It is also better capable of vectorization, so this is where the improvement general comes from. Gfortran is covering any CPU out there. I have some profiling data from Vtune from last year. How should I share it with you?

The speedup is not entirely comparable since Lukas tried on two different clusters but I had also seen something like 5-fold increase in performance on my desktop at home. What CPUs are on the Norwegian cluster? On Taito there are Sandy Bridge Xeon E5-2670 and Haswell Xeon E5-2690v3. The Haswell have AVX2 and FMA instructions, so that already gives an improvement in mathematical operations.

**Comment by heikef** [comment]
Yes, the other way around makes more sense. -)) Which molecule did you use for your tests?

**Comment by mariavd** [comment]
Benzene and, probably, dibenzopentalene. I was testing different number of grid points, for example. So where should I copy the data?

**Comment by bast** [comment]
Are the input files large?

**Comment by bast** [comment]
I will verify whether I can reproduce this with my benchmarks.

**Comment by mariavd** [comment]
A quick comment: 

A 3D current density calculation on a benzene dimer with 1282752 grid points:
Taito (gcc): 35295.97 s estimated (unknown whether it went to Sandy bridge or Haswell)
My desktop (ifort): 4875.96 s estimated (Ivy bridge but overclocked to 4.6 GHz -> so not really a fair comparison with the Xeons)

I am planning to run Vtune on Taito since it will be a more realistic benchmark. The ones that I have done before (and I promise to dig them out this weekend) were on the desktop.

**Comment by bast** [comment]
Do you see a difference between compilers on the same machine?

**Comment by mariavd** [comment]
My own memory has faded, I can't find where the profiling data is. I will have to do new tests. Let's see if I have some time tomorrow evening for that.

**Comment by heikef** [comment]
@mariavd no stress. We have all a lot on our to do list.

**Comment by heikef** [comment]
Closing the issue. It is outdated and currently not relevant any more. We can reopen it when needed be.
