### ISSUE TITLE
Youtube channel with examples

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#180]
This idea is from Maria @mariavd 

I think this is very useful and would make user support much easier. It could be part of the documentation to make gimic usage more convenient for new users.

**Comment by mariavd** [comment]
This is the channel I made. It is registered with a gmail account, so that could possibly be used as another way for other users to ask for help. I can give you the password. There are few users but possibly one could think of making a mailing list to update them about new features. 

[qmcurrents@gmail.com](qmcurrents@gmail.com)

[Youtube channel](https://www.youtube.com/channel/UC_5dN4qhYTOtr-itnsjoE0w/videos)

There are just two videos and I started making a longer one but it isn't ready yet. I am using Icecream Screen Recorder. The free version limits you to 5 min but one can plan properly and record the video in pieces if needed. The output files can be converted to MP4 with Handbrake. Then I stitching it together in VSDC but  I don't remember if it has a Mac or Linux version.

**Comment by bast** [comment]
Very cool!

**Comment by heikef** [comment]
Thank you Maria! Great initiative! This is a very good idea. A direct contact to users to inform them about new features will be very useful in the future assuming that people want to use our program. Would it be possible to link the youtube channel to the documentation? If this is ok for you then please file a pull request and close the issue.

**Comment by mariavd** [comment]
Yes, I have started writing a new page for the documentation but I'm not ready yet. It is here for now:

https://github.com/mariavd/gimic/blob/docs/doc/interpretation.rst

**Comment by heikef** [comment]
So far we got only very positive user feedback regarding the YouTube channel of @mariavd

**Comment by heikef** [comment]
I saw that links to the Youtube channel / examples have been included in the documentation. I will close the issue.
