### ISSUE TITLE
Please check the integration profile

### ISSUE THREAD

**Issue by patrashantigopal** [qmcurrents/gimic#236]
I have performed the integration profile for pyrrole. I shall be extremely helpful if someone can check my calculation. Looking forward.

Best regard,
[current_profile_pyrrole.zip](https://github.com/qmcurrents/gimic/files/3077552/current_profile_pyrrole.zip)

Shanti

**Comment by heikef** [comment]
You have to make sure that the black curve starts at zero. So your starting point is not well chosen. So you loose some contributions. Otherwise it looks fine. When looking at more complicated systems you should always make sure that the diatropic current is on the outside. Always check also for warnings like "left handed coordinate system" because then the B field is automatically flipped by the program. 

I see you managed to install the interactive bash scripts. Very good!

**Comment by patrashantigopal** [comment]
Thank you for your reply. I started the integration from the centroid of the ring. Should I start it from the midpoint of the bond towards outside of the ring?

**Comment by heikef** [comment]
It is correct to start it from the ring center but the vortex of your current is not necessarily always in the geometric center. Therefore, it is better to extend the dimensions of your step integration a bit and sum from the zero point (where the black curve (total current strength) is zero to the outside.  You can do an integration across the whole molecule to see how the curves + sign of the curves are changing. Then you understand better what I mean.

**Comment by patrashantigopal** [comment]
Please tell me how to do the integration for the whole molecule?

**Comment by heikef** [comment]
I meant across the whole molecule. This means you extend your integration plane. Your width is at the moment something like from -2 to 6 (guessing) and you could do something like from -15 to + 6 so you change the dimension of your plane. Like cutting with a knive across the cake and not starting in the center of the cake.

**Comment by patrashantigopal** [comment]
Thank you. I understand. I will try to do as you suggested and will report to you.

**Comment by heikef** [comment]
Hm, this is 14 days old. I assume things are working for you and will close this issue.
