### ISSUE TITLE
cmake and numgrid integration into gimic

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#277]
@bast would it be possible to automatically integrate numgrid into gimic by installing everything via cmake? Maybe @lnw has also an idea/opinion about this? Or would it just complicate everything?

**Comment by bast** [comment]
Just for clarification: this is to be able to use the C interface? Or is this for the Python interface?

**Comment by heikef** [comment]
We are using the python interface.

**Comment by heikef** [comment]
Is numgrid working with python3?

**Comment by bast** [comment]
If we are using the Python interface, then I would not bake this into CMake. But rather we give the user the freedom to install it into a virtual environment or a Conda environment.

But we can use CMake to verify that it is available.

Numgrid should work with Python 3, otherwise it is a bug. Note also that a new version of Numgrid is coming up soon (inside it has been completely rewritten).

**Comment by heikef** [comment]
Great. Does this influence the mk_grid.py file? I mean do we need to adapt it? 
If cmake finds numgrid one could add an option if the user wants to install it or not. Like numgrid=on/off.

**Comment by bast** [comment]
There might be some API changes but of course I will help adapting the file. It will become faster and more robust.

I would not let CMake handle the installation of Python dependencies. This I think is best left to Conda or venv. But we can let it verify and give hints on how to install it.

**Comment by heikef** [comment]
OK. I checked with Anaconda3 one can install numgrid and also runtest when installing before pip.
