### ISSUE TITLE
Input keywords discussion

### ISSUE THREAD

**Issue by heikef** [qmcurrents/gimic#90]
@mariavd contacted me - input keywords like 
- in 
- out
- up 
- down
should be kept - I do not know why they got removed - must have been part of a long long time ago clean up process

**Comment by bast** [comment]
I don't want to be always criticizing but for future I recommend to make issues more fine-grained, such as "Reintroduce keyword X" or "Suggestion to remove keyword Y". If the topic is too wide, it can never be resolved. But it might be OK to discuss keywords in general if this is what we want to do here.

**Comment by heikef** [comment]
I see your point. The keywords in, out, up and down belong together. It does not make sense to reintroduce only one since it is equivalent to width and height keywords, which I personally prefer. However, Maria prefers the other keywords for scripting reasons.

**Comment by heikef** [comment]
I will reintroduce the other keywords as extra issues.

**Comment by mariavd** [comment]
@heikef  The keywords and input need a bit more discussion. When I was trying to fix one part of the script I ended up with something weird. I am not getting into details because it is related to my scripts, so no need to bother with their structure. Maybe we should ignore the keywords for the moment because I my focus in on my other projects instead of the scripts.

**Comment by heikef** [comment]
OK - I filled two extra issues. We can take things up there if needed.
